/** English labels for the theme editor (replaces i18n keys from Inimark). */

export const THEME_SECTION_LABELS: Record<string, string> = {
  groupChrome: "Chrome & surfaces",
  groupBody: "Editor body",
  groupCodeBlock: "Code blocks",
  groupCodeInline: "Inline code",
  groupBlockquote: "Blockquote",
  groupMetadata: "Metadata",
  groupTable: "Table",
  groupTag: "Tags",
  groupScrollbar: "Scrollbar",
  groupCodeHighlight: "Syntax highlighting",
};

export const THEME_TOKEN_LABELS: Record<string, string> = {
  bgSecondary: "Secondary background",
  bgSurface: "Surface",
  bgHover: "Hover",
  bgTertiary: "Tertiary background",
  bgInput: "Input background",
  border: "Border",
  accent: "Accent",
  accentHover: "Accent hover",
  danger: "Danger",
  bgPrimary: "Primary background",
  textPrimary: "Primary text",
  textSecondary: "Secondary text",
  textTertiary: "Tertiary text",
  textStrong: "Strong text",
  bgCode: "Code block background",
  bgCodeInline: "Inline code background",
  textCode: "Inline code text",
  blockquoteBorder: "Blockquote border",
  blockquoteBg: "Blockquote background",
  blockquoteText: "Blockquote text",
  metadataBg: "Metadata background",
  metadataBorder: "Metadata border",
  tableHeaderBg: "Table header",
  tableCellBg: "Table cell",
  tagBg: "Tag background",
  tagText: "Tag text",
  tagBorder: "Tag border",
  scrollbarThumb: "Scrollbar thumb",
  scrollbarThumbHover: "Scrollbar thumb hover",
  scrollbarTrack: "Scrollbar track",
  sidebarChromeOpacity: "Sidebar chrome opacity",
  radiusCodeBlock: "Code block radius",
  radiusCodeInline: "Inline code radius",
  paddingCodeInlineY: "Inline code padding Y",
  paddingCodeInlineX: "Inline code padding X",
  blockquoteBorderWidth: "Blockquote border width",
  paddingBlockquoteY: "Blockquote padding Y",
  paddingBlockquoteX: "Blockquote padding X",
  radiusMetadata: "Metadata radius",
  marginMetadataBottom: "Metadata bottom margin",
  radiusTable: "Table radius",
  radiusTag: "Tag radius",
  paddingTagY: "Tag padding Y",
  paddingTagX: "Tag padding X",
  radiusScrollbar: "Scrollbar radius",
  scrollbarSize: "Scrollbar size",
  hljsKeyword: "Keywords",
  hljsString: "Strings",
  hljsComment: "Comments",
  hljsNumber: "Numbers",
  hljsBuiltIn: "Built-ins",
};

export const BUILTIN_THEME_LABELS: Record<string, string> = {
  white: "White",
  mint: "Mint",
  "mint-dark": "Mint Dark",
  "modern-dark": "Modern Dark",
  "claude-code": "Claude Code",
  purple: "Purple",
  hermes: "Hermes",
  next: "NexT",
  slate: "Slate",
  ocean: "Ocean",
};

export function themeLabel(key: string, fallback?: string): string {
  return THEME_TOKEN_LABELS[key] ?? THEME_SECTION_LABELS[key] ?? fallback ?? key;
}
