/**
 * Pack theme CSS for the published site.
 * Callers pass raw CSS for builtin themes.css (or custom packs) plus editor prose CSS.
 */
export function packSiteCss(options: {
  layoutCss: string;
  themeVariablesCss: string;
  editorWidgetsCss: string;
  editorThemeCss: string;
}): string {
  return [
    "/* generated by @inimark/site-render — do not edit */",
    options.themeVariablesCss.trim(),
    options.editorWidgetsCss.trim(),
    options.editorThemeCss.trim(),
    options.layoutCss.trim(),
  ]
    .filter(Boolean)
    .join("\n\n");
}
